language: node_js
node_js:
  - "node"
dist: trusty
sudo: false

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - node_modules

script:
  - cd angular-url-shortener
  - ng build --prod --base-href https://sergiosv96.github.io/url-shortener/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-url-shortener
  on:
    branch: gh-pages
